development:
  short_name: <%= ENV["SHORT_NAME"] %>
  domain: 'localhost:3002'
  dictionary_url: localhost

test:
  short_name: localhost
  domain: localhost
  dictionary_url: localhost

production:
  short_name: <%= ENV["SHORT_NAME"] %>
  domain: <%= ENV["DOMAIN"] %>
  dictionary_url: <%= ENV["DICTIONARY_URL"] %>
