require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtisansController do

  # This should return the minimal set of attributes required to create a valid
  # Artisan. As you add validations to Artisan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "Paco" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtisansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all artisans as @artisans" do
      artisan = Artisan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:artisans).should eq([artisan])
    end
  end

  describe "GET show" do
    it "assigns the requested artisan as @artisan" do
      artisan = Artisan.create! valid_attributes
      get :show, {:id => artisan.to_param}, valid_session
      assigns(:artisan).should eq(artisan)
    end
  end

  describe "GET new" do
    it "assigns a new artisan as @artisan" do
      get :new, {}, valid_session
      assigns(:artisan).should be_a_new(Artisan)
    end
  end

  describe "GET edit" do
    it "assigns the requested artisan as @artisan" do
      artisan = Artisan.create! valid_attributes
      get :edit, {:id => artisan.to_param}, valid_session
      assigns(:artisan).should eq(artisan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Artisan" do
        expect {
          post :create, {:artisan => valid_attributes}, valid_session
        }.to change(Artisan, :count).by(1)
      end

      it "assigns a newly created artisan as @artisan" do
        post :create, {:artisan => valid_attributes}, valid_session
        assigns(:artisan).should be_a(Artisan)
        assigns(:artisan).should be_persisted
      end

      it "redirects to the created artisan" do
        post :create, {:artisan => valid_attributes}, valid_session
        response.should redirect_to(Artisan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved artisan as @artisan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artisan.any_instance.stub(:save).and_return(false)
        post :create, {:artisan => { "name" => "invalid value" }}, valid_session
        assigns(:artisan).should be_a_new(Artisan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artisan.any_instance.stub(:save).and_return(false)
        post :create, {:artisan => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested artisan" do
        artisan = Artisan.create! valid_attributes
        # Assuming there are no other artisans in the database, this
        # specifies that the Artisan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Artisan.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => artisan.to_param, :artisan => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested artisan as @artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => valid_attributes}, valid_session
        assigns(:artisan).should eq(artisan)
      end

      it "redirects to the artisan" do
        artisan = Artisan.create! valid_attributes
        put :update, {:id => artisan.to_param, :artisan => valid_attributes}, valid_session
        response.should redirect_to(artisan)
      end
    end

    describe "with invalid params" do
      it "assigns the artisan as @artisan" do
        artisan = Artisan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artisan.any_instance.stub(:save).and_return(false)
        put :update, {:id => artisan.to_param, :artisan => { "name" => "invalid value" }}, valid_session
        assigns(:artisan).should eq(artisan)
      end

      it "re-renders the 'edit' template" do
        artisan = Artisan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Artisan.any_instance.stub(:save).and_return(false)
        put :update, {:id => artisan.to_param, :artisan => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested artisan" do
      artisan = Artisan.create! valid_attributes
      expect {
        delete :destroy, {:id => artisan.to_param}, valid_session
      }.to change(Artisan, :count).by(-1)
    end

    it "redirects to the artisans list" do
      artisan = Artisan.create! valid_attributes
      delete :destroy, {:id => artisan.to_param}, valid_session
      response.should redirect_to(artisans_url)
    end
  end

end
